### ISSUE TITLE
About the raw_bag file time offsets

### ISSUE THREAD

**Issue by FORREST1901** [daniilidis-group/m3ed#13]
Your dataset includes a wide variety of scenes and motion platforms, making it a unique and valuable resource in the Event Cameras field. It addresses some gaps that many other datasets don't cover. I'm hoping to use your dataset and cite your work, I have a few questions for usage:

1. I'm working with ROS and need to handle rosbags that contain different types of data. You offer a raw bag download, but the website mentions that 'These files are not time corrected and events are stored in binary format.' How should I go about time calibrating the data in the rosbag, and where can I find the corresponding time offsets?

2. The Calibrations section doesn't seem to match the dataset, their names and the number of files are not directly the same. How can I find the most accurate calibration results for a give data file? Thanks for your help

**Comment by fcladera** [comment]
Hi Forrest,
1. The raw bags that we offer to download is the data that robots recorded. This data is not synchronized: different sensors and hardware interfaces may buffer data in different ways, and there is no guarantee when the bag is written into the disk. We included however synchronization signals in all the data, and that is what we used to generate the synchronized bags. If you are interested in how this process works, you can take a look into the [rosbag2timecorrections.py](https://github.com/daniilidis-group/m3ed/blob/main/build_system/bag_processing/rosbag2timecorrection.py) file. If you really need ROS bags, we would suggest reconstructing them from the hdf5 files.

2. The file [dataset_list.yaml](https://github.com/daniilidis-group/m3ed/blob/main/dataset_list.yaml) defines which calibration file was used for each data file. Calibrations are [embedded in the h5 data files](https://github.com/daniilidis-group/m3ed/blob/7a9a96b84e1824c0291e8819d0468080b42b4752/build_system/bag_processing/rosbag2hdf5.py#L871) by reading the Kalibr output and just copying the calibration output. The association between data files and calibrations was done manually, and we considered the following:
   1. Temporal consistency. Multiple calibrations were recorded at the beginning and at the end of an experiment.
   2. Quality of the calibration: We considered the kalibr report (available to download), the number of camera poses, the coverage of the FoV of the cameras.
   
Let us know if you have any other questions!
