### ISSUE TITLE
The ratio of inf pixels in depth map is big.

### ISSUE THREAD

**Issue by HTLeoo** [daniilidis-group/m3ed#2]
Hi, authors,
I notice that the ratio of invalid depth pixels is too big. 
I use ‘car_urban_night_rittenhouse_gt’ and 'car_urban_night_city_hall_gt' as examples.

I use the code below to compute the number of invalid depth maps.
```
for i in tqdm(range(len(gt_f['depth/prophesee/left']))):
    depth = gt_f['depth/prophesee/left'][i] #(720, 1280)
    if np.sum(depth == np.inf)/(720*1280) > 0.99:
        invalid_depth_count+=1
print(invalid_depth_count)
```
The two results are both the lengths of the sequence.

**Comment by fcladera** [comment]
Hi @HTLeoo

Depth pixels are quite sparse, as they are captured with a rotating Lidar that has 64 vertical channels. We have added depth videos in the download section of the dataset:

https://m3ed.io/download/

For instance, this is a [sample sequence](https://m3ed-dist.s3.us-west-2.amazonaws.com/processed/car_urban_day_penno_small_loop/car_urban_day_penno_small_loop_depth_gt.mp4).

You may create a mesh from the LiDAR PC if you intend to use it in your algorithm. We decided not to do it as Lidar (in the GT file) is intended to be used as ground truth.
